### ISSUE TITLE
You did not provide the number of bytes specified by the Content-Length HTTP header when Multiple file upload to s3 

### ISSUE THREAD

**Issue by JianJie-Li** [AFNetworking/AFNetworking#3622]
when i tried to upload a large image to s3 ,process always fail with below error ：
com.amazonaws.services.s3.model.AmazonS3Exception: You did not provide the number of bytes specified by the Content-Length HTTP header (Service: Amazon S3; Status Code: 400; Error Code: IncompleteBody; Request ID: 30B803D530A358E7)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1369) ~[aws-java-sdk-core-1.10.53.jar:na]
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:913) ~[aws-java-sdk-core-1.10.53.jar:na]
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:631) ~[aws-java-sdk-core-1.10.53.jar:na]
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:400) ~[aws-java-sdk-core-1.10.53.jar:na]
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:362) ~[aws-java-sdk-core-1.10.53.jar:na]
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:311) ~[aws-java-sdk-core-1.10.53.jar:na]
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3673) ~[aws-java-sdk-s3-1.10.53.jar:na]
    at com.amazonaws.services.s3.AmazonS3Client.doUploadPart(AmazonS3Client.java:2809) ~[aws-java-sdk-s3-1.10.53.jar:na]
    at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:2794) ~[aws-java-sdk-s3-1.10.53.jar:na]
    at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadPartsInSeries(UploadCallable.java:255) ~[aws-java-sdk-s3-1.10.53.jar:na]
    at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInParts(UploadCallable.java:189) ~[aws-java-sdk-s3-1.10.53.jar:na]
    at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:121) ~[aws-java-sdk-s3-1.10.53.jar:na]
    at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:139) ~[aws-java-sdk-s3-1.10.53.jar:na]
    at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:47) ~[aws-java-sdk-s3-1.10.53.jar:na]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[na:1.7.0_79]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_79]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_79]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]

there is my source code:

```
    public void initiateMultipartUploadHighAPI(String fileMD5)
{
    this.entireFileMD5 = fileMD5;
    ThreadPoolExecutor executor = new ThreadPoolExecutor(3, 5, 60, TimeUnit.SECONDS, new LinkedBlockingQueue<Runnable>(1000)); 
        tm = new TransferManager(defClient.client, executor); 
    TransferManagerConfiguration config = new TransferManagerConfiguration();
    config.setMultipartUploadThreshold(5*1024*1024);//when file size over the threshold ,then automatically use a multipart upload strateg 
    config.setMinimumUploadPartSize(128*1024); //minimum upload part size
    tm.setConfiguration(config);
}

public void multipartUploadHighAPI(InputStream is) throws Exception
{
    String key = S3PersonalFileMgr.getS3Path(entireFileMD5, "image/jpg");
    ObjectMetadata objectMetadata = new ObjectMetadata();
    objectMetadata.setContentLength(22054059l);
    objectMetadata.setContentMD5(entireFileMD5);
    PutObjectRequest request = new PutObjectRequest(defClient.bucketName, key, is, objectMetadata);

    Upload upload = tm.upload(request);

    //Transfer allows you to set a ProgressLisntener to receive asynchronous notifications about your transfer's progress.
    upload.addProgressListener(new ProgressListener()
    {
        @Override
        public void progressChanged(ProgressEvent progressEvent)
        {
            System.out.println("Transferred bytes : " + progressEvent.getBytesTransferred());
        }
    });

    try
    {
        upload.waitForCompletion();
    } catch (AmazonClientException | InterruptedException e)
    {
        logger.info("Unable to upload file,upload was aborted : {}",e);
    }
}
```

**Comment by StanOz** [comment]
Look at this. https://github.com/AFNetworking/AFNetworking/issues/1398
