### ISSUE TITLE
pod install  issues  help

### ISSUE THREAD

**Issue by xcmg** [AFNetworking/AFNetworking#3759]
```
/Users/ocean/.rvm/rubies/ruby-2.2.2/bin/pod install
```
### Report
- What did you do?
- What did you expect to happen?
- What happened instead?
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/ocean/.rvm/rubies/ruby-2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a9a2d85041bb83171164877406d1ba5dfa51e002
```
### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa

platform :ios, '8.0'

target 'link' do
pod 'AFNetworking', '~> 3.0'
end
```
### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/xcodeproj-1.3.0/lib/xcodeproj/project.rb:217:in `initialize_from_file'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/xcodeproj-1.3.0/lib/xcodeproj/project.rb:102:in `open'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:695:in `block (2 levels) in inspect_targets_to_integrate'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:694:in `each'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:694:in `block in inspect_targets_to_integrate'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:689:in `inspect_targets_to_integrate'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/ocean/.rvm/rubies/ruby-2.2.2/bin/pod:23:in `load'
/Users/ocean/.rvm/rubies/ruby-2.2.2/bin/pod:23:in `<main>'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/bin/ruby_executable_hooks:15:in `eval'
/Users/ocean/.rvm/gems/ruby-2.2.2@global/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5BXcodeproj%5D+Unknown+object+version.&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

help!

**Comment by skyline75489** [comment]
This seems to be a issue of CocoaPods, not AFNetworking.
